application: ebfmex-pub
version: movil
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /backend/.*
  script: backend.py
  #login: admin

- url: /.*
  script: main.py

libraries:
- name: jinja2
  version: latest

- name: django
  version: latest
