application: ebfmxorg
version: movil
runtime: python27
api_version: 1
threadsafe: false

#default_expiration: "1d"

builtins:
- remote_api: on

handlers:
- url: /backend/reportectas.csv
  script: backend.py
  #login: admin

- url: /backend/gensearch
  script: backend.py
  login: admin

- url: /backend/searchinit
  script: backend.py
  login: admin

- url: /backend/sit
  script: backend.py
  login: admin

- url: /backend/countsids
  script: backend.py
  login: admin

- url: /backend/.*
  script: backend.py
#  login: admin

- url: /.*
  script: main.py

libraries:
- name: jinja2
  version: latest

- name: django
  version: latest
